### ISSUE TITLE
Login for private profiles

### ISSUE THREAD

**Issue by canarybearer** [milo2012/osintstalker#3]
Unable to login to parse friend's profile

**Comment by TheOncomingStorm** [comment]
I'm having a similar problem. 

I found the username and password variables in fbstalker.py and got it to login but once it logs in it seems to log right back out. 

Ok, the problem is that when FB detects you logging in from a new browser it puts that stupid message and unless you deal with that by clicking on the appropriate button, it apparently logs you out.  To deal with that I put a time.sleep(10) right after the login so I could click the button and proceed and it seems to work.

**Comment by milo2012** [comment]
theOncomingStorm Thank you for commenting on this.  I will try it out with another account and see if I can write some code to react to that prompt.
